#!/bin/bash

set -o noclobber
set -o nounset
set -o pipefail
shopt -s dotglob
shopt -s extglob
shopt -s globstar
shopt -s nullglob

function parse_parametric_eq {
    hz=''
    gain=''
    q=''
    while read -r line
    do
        if [[ "$line" = '' ]]; then break; fi
        echo "# $line"

        if [[ -z "$hz" ]]
        then
            hz="${line#'Parameter "Center freq (Hz)" = '}"
            if [[ "$hz" = "$line" ]]; then hz=''; fi
        fi

        if [[ -z "$gain" ]]
        then
            gain="${line#'Parameter "Boost (dB)" = '}"
            if [[ "$gain" = "$line" ]]; then gain=''; fi
        fi

        if [[ -z "$q" ]]
        then
            q="${line#'Parameter "Q (RBJ)" = '}"
            if [[ "$q" = "$line" ]]; then q=''; fi
        fi
        if [[ -z "$q" ]]
        then
            q="${line#'Q (RBJ) = '}"
            if [[ "$q" = "$line" ]]; then q=''; fi
        fi
    done

    # Try to work around Equalizer APO bug https://sourceforge.net/p/equalizerapo/tickets/141/
    if [[ "${hz%.*}" != "$hz" ]]; then hz+='000'; fi

    echo "Filter: ON PK Fc $hz Hz Gain $gain dB Q $q"
    echo
}

function parse_delay_block {
    msec=''
    while read -r line
    do
        if [[ "$line" = '' ]]; then break; fi
        echo "# $line"

        if [[ -z "$msec" ]]
        then
            msec="${line#'Parameter "Delay (msec)" = '}"
            if [[ "$msec" = "$line" ]]; then msec=''; fi
        fi
    done

    if [[ "${msec:0:1}" = '-' ]]
    then
        echo "Delay blocks with negative delay ($msec msec) are unsupported, skipping" >&2
        return
    fi

    echo "Delay: $msec ms"
    echo
}

function parse_gain_block {
    db=''
    while read -r line
    do
        if [[ "$line" = '' ]]; then break; fi
        echo "# $line"

        if [[ -z "$db" ]]
        then
            db="${line#'Parameter "Gain (dB)" = '}"
            if [[ "$db" = "$line" ]]; then db=''; fi
        fi
    done

    echo "Preamp: $db dB"
    echo
}

function parse_pf {
    hz=''
    while read -r line
    do
        if [[ "$line" = '' ]]; then break; fi
        echo "# $line"

        if [[ -z "$hz" ]]
        then
            hz="${line#'Parameter "Cutoff freq (Hz)" = '}"
            if [[ "$hz" = "$line" ]]; then hz=''; fi
        fi
    done

    # Try to work around Equalizer APO bug https://sourceforge.net/p/equalizerapo/tickets/141/
    if [[ "${hz%.*}" != "$hz" ]]; then hz+='000'; fi

    echo "Filter: ON $1 Fc $hz Hz"
    echo
}
function parse_hpf {
    parse_pf "HP"
}
function parse_lpf {
    parse_pf "LP"
}

while read -r line
do
    if [[ "$line" = '' ]]; then continue; fi

    type="${line#*: }"
    case "$type" in
        'Parametric EQ') parser_type='parametric_eq';;
        'Parametric EQ (RBJ)') parser_type='parametric_eq';;
        'Delay Block') parser_type='delay_block';;
        'Gain Block') parser_type='gain_block';;
        'HPF Butterworth 12 dB/oct') parser_type='hpf';;
        'LPF Butterworth 12 dB/oct') parser_type='lpf';;
        *)
            echo "Filter type '$type' unsupported, skipping" >&2
            while read -r line
            do
                if [[ "$line" = '' ]]; then break; fi
            done
            continue
    esac
    echo "# $line"
    "parse_$parser_type"
done
